import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { Inter } from 'next/font/google';

import '../globals.css';
import StyledComponentsRegistry from '../lib/registry';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return [{ lang: 'en-US' }, { lang: 'fr' }];
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <head>
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no" />
      </head>
      <body className={inter.className}>
        <Theme>
          <StyledComponentsRegistry>
            <NextIntlClientProvider locale={locale} messages={messages}>
              <ClerkProvider appearance={{ baseTheme: dark }}>{children}</ClerkProvider>
            </NextIntlClientProvider>
          </StyledComponentsRegistry>
        </Theme>
      </body>
    </html>
  );
}
